// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	FirstName string `json:"first_name" bson:"first_name"`
	LastName  string `json:"last_name" bson:"last_name"`
	Phone     string `json:"phone" bson:"phone"`
	Email     string `json:"email" bson:"email"`
	CreatedAt string `json:"created_at" bson:"created_at"`
}

type User struct {
	ID        string `json:"id" bson:"_id"`
	CreatedAt string `json:"created_at" bson:"created_at"`
	FirstName string `json:"first_name" bson:"first_name"`
	LastName  string `json:"last_name" bson:"last_name"`
	Phone     string `json:"phone" bson:"phone"`
	Email     string `json:"email" bson:"email"`
}
